### ISSUE TITLE
NuGet package is out of sync with repository

### ISSUE THREAD

**Issue by CoreDumpSoftware** [SerhiiVoznyi/Ticketmaster-SDK#11]
I'm trying to use your API when I noticed that the Event model doesn't include a Dates property.  It looks like you made a change to this file back in April but never updated the NuGet package.

**Comment by SerhiiVoznyi** [comment]
Updated NuGet, sorry for the delay. In case of any issues or suggestions for improvements do not hesitate to contact me directly in facebook twitter or any other social media.
