### ISSUE TITLE
What is the intended way to page results?

### ISSUE THREAD

**Issue by RobThree** [SerhiiVoznyi/Ticketmaster-SDK#12]
Suppose I have this code
```c#
var config = new Config("myapikey");
var factory = new ClientFactory();
var discovery = factory.Create<DiscoveryApi>(config);

// Prepare request
var req = new SearchEventsRequest();
req.AddQueryParameter(SearchEventsQueryParameters.countryCode, "NL");
req.AddQueryParameter(SearchEventsQueryParameters.size, "200");
req.AddQueryParameter(SearchEventsQueryParameters.sort, "date,name,asc");
req.AddQueryParameter(SearchEventsQueryParameters.classificationId, "KZFzniwnSyZfZ7v7nJ");

// Retrieve result
var result = await discovery.Events.SearchEventsAsync(req);

// Dump some data
foreach (var e in result._embedded.Events)
    Console.WriteLine(e.Name);

// What is the best way to retrieve page 2?
```

What is the best way to retrieve page 2? And 3? How would I iterate all pages? One way I tried is:

```c#
var result = await discovery.Events.SearchEventsAsync(req);
while (result.Page.Number < result.Page.TotalPages)
{
    foreach (var e in result._embedded.Events)
        Console.WriteLine(e.Name);
    req.AddQueryParameter(SearchEventsQueryParameters.page, (result.Page.Number + 1).ToString());
}
```
But this is ugly (requiring the `(result.Page.Number + 1).ToString()` and also requires me to create a **new** request each iteration, since for the next page it will throw an exception that the "Page" argument is already in the request.

What would be the correct / preferred / best / intended way to do paging?

Also: Maybe you could consider adding a few overloads on `AddQueryParameter` so that integers, date(time)s etc. are also accepted and converted to a string internally? (That would also save me from having to find out which date(time)format the API expects ('YYYY-MM-DD' or 'MM-DD-YYYY' or 'YYYY-MM-DDTHH:mm:ss' or... Why would I care, let this SDK handle it for me?).

Finally: What's up with the `_embedded` in `result._embedded.Events` ? Why not `result.Events` or something?

**Comment by RobThree** [comment]
> Do you see a problem here?

No, to be honest, I'm a bit confused. I'll try to see if I can find in the docs what you're saying. Thanks for looking into it anyway! 👍

**Comment by SerhiiVoznyi** [comment]
Hi Rob (@RobThree) , take a look into this: https://github.com/SerhiiVoznyi/Ticketmaster-SDK/blob/functionality/develop/src/Ticketmaster.Discovery.Tests/V2/Extensions/SearchEvents.cs

try to debug fetching process you will see what I mean.
