### ISSUE TITLE
TradeDesk Support

### ISSUE THREAD

**Issue by carvajalluis** [SerhiiVoznyi/Ticketmaster-SDK#13]
Hello There, 

I'm trying to implement this new ( at least to me ) trade desk API  into a broker app so that they can  manage  digital ticketing transfers  with 

is the trade desk covered?is there any transfer client?

**Comment by SerhiiVoznyi** [comment]
Hi @carvajalluis, this functionality was not covered yet. This is open source library and any help is appreciated. Btw, I am planing to provide this functionality, it should be finished until 17.12.2019

**Comment by SerhiiVoznyi** [comment]
FYI, Ticketmaster moved all replaced all thair SDK by https://developer.ticketmaster.com/partners/certified-partners/mobile-app-developers/
which allowed to 'Certified Partners', this SDK - is an open-source client, targeted on OPEN APIs only, such as Discovery API

**Comment by carvajalluis** [comment]
thanks for the response. I'm no longer involved in that particular project, great work you have done, I had to make a generic API client though, thinking ahead as there is always new  third party integrations in that project. Seems to me the integration ecosystem of TicketMaster is a bit poor  for such enterprise, the documentation is also scarce. cheers
